### ISSUE TITLE
crypto_box_easy return value undocumented

### ISSUE THREAD

**Issue by paulharris** [jedisct1/libsodium-doc#120]
Hi, here is a simple one,

The function crypto_box_open_easy() has the following documentation:
`The function returns -1 if the verification fails, and 0 on success. On success, the decrypted message is stored into m.`

But there is no specific mention of crypto_box_easy()'s return value.

It is implied it returns an error number in the example at the top, but it would also be nice to know what could go wrong during crypto_box_easy() (and it's sibling functions).
I do like that the compiler warned me that I didn't check the result of crypto_box_detached() - I would like to see warnings attached to all of the functions that return error messages!

This lack of this kind of specific documentation is in a few places throughout,
for example, on the same page,
crypto_box_keypair() returns an int, but it is not documented anywhere whether the caller should check the result. 
And in this case, the example code does *not* check the return result.
`crypto_box_keypair(alice_publickey, alice_secretkey);`

So in this case, I can't tell whether I should be checking the result or not.

It would be good to do an audit to ensure all functions that return a value have that return value documented.

Thanks for the great library and documentation!

**Comment by jedisct1** [comment]
Generally a return value of `0` means success, and `-1` that something went wrong.

Functions such as `crypto_box_keypair()` can't fail. The return value is only there for ABI compatibility with NaCl.

So, checking it is not important. It wouldn't hurt either.
