### ISSUE TITLE
Do crypto_pwhash_str* functions have password length requirements like crypto_pwhash?

### ISSUE THREAD

**Issue by jprjr** [jedisct1/libsodium-doc#124]
Hi there, I'm going through the documentation for `crypto_pwhash_str` and `crypto_pwhash_str_verify`.

I noticed that `crypto_pwhash` requires `passwdlen` to be between `PASSWD_MIN` and `PASSWD_MAX`. `crypto_pwhash_str` and `crypto_pwhash_str_verify` don't mention if there's a minimum/maximum length for `passwdlen`, I just wanted to check on that.

Happy to update the docs and open a PR

**Comment by jedisct1** [comment]
They do. But the minimum password length is `0` and the maximum is `4294967295`, so there's no practical limit. 

These constants are there for consistency, but are pretty much useless and application developers shouldn't worry about these limits.
