### ISSUE TITLE
Suggestion: Specify values of constants

### ISSUE THREAD

**Issue by samuel-lucas6** [jedisct1/libsodium-doc#126]
Since the constants for functions are listed in the documentation, I think it would be beneficial if the values of the constants were listed there as well, so the information is centralised in one place. For example:

> **Constants**
> - crypto_aead_xchacha20poly1305_ietf_KEYBYTES = 32
> - crypto_aead_xchacha20poly1305_ietf_NPUBBYTES = 24
> - crypto_aead_xchacha20poly1305_ietf_ABYTES = 16

I appreciate that this would be annoying to update if you had to change anything, but surely these values never get amended for most functions.

**Comment by jedisct1** [comment]
Well, the purpose of these macros/functions is to avoid applications using the values directly.

And yes, some of them do change. That happened for parameters related to password hashing functions for example.
