### ISSUE TITLE
what does 'nm' in _beforenm / __afternm  means?

### ISSUE THREAD

**Issue by byronhe** [jedisct1/libsodium-doc#25]
https://download.libsodium.org/doc/public-key_cryptography/authenticated_encryption.html

it looks like crypto_box_curve25519xsalsa20poly1305_beforenm() is doing a curve25519 ECDH key exchange/scalarmult, but what does 'nm' means ? it looks confusing.

**Comment by jedisct1** [comment]
`nm` stands for `nonce and message`.

`beforenm` prepares a context that can later be used with multiple nonce+message pairs.
