### ISSUE TITLE
download.libsodium.org website bug

### ISSUE THREAD

**Issue by robehickman** [jedisct1/libsodium-doc#26]
I've been experiencing an issue with this content displayed at download.libsodium.org. The first page loads fine, and the first link in the side navigation also loads fine.  From that point on clicking the links in the side navigation does not do anything, and refreshing the browser results in a 404 page.

The same content displayed at https://jedisct1.gitbooks.io/libsodium/content/ does not have this problem. This link was found by "John Q NotSoPublic" on the GRC SQRL newsgroups, who has confirmed the same issue.

Sodium is a very well structured and thought out library, but having an issue like this on the main website could put people off using it. To begin with I thought the 404 pages meant that most of the sites pages where missing, which is not actually the case.

**Comment by jedisct1** [comment]
Looks like Gitbook made some changes to their themes and are now using absolute links :(

An extra rewrite rule has been added, and everything should work as expected again.
