### ISSUE TITLE
randombytes_keygen reference

### ISSUE THREAD

**Issue by justin1121** [jedisct1/libsodium-doc#69]
Hi,

I cannot seem to find any reference in the code to the `randombytes_keygen` function even though its listed here in the docs. Am I missing something?

Thanks!

**Comment by jedisct1** [comment]
Indeed, there is no `randombytes_keygen()` function. There isn't any in libhydrogen either.

It probably doesn't make sense to have one, so the documentation has been updated.

Thanks!
