### ISSUE TITLE
Status of the roadmap

### ISSUE THREAD

**Issue by Syndace** [jedisct1/libsodium-doc#70]
Yo!

How up-to-date is the roadmap rendered [here](https://libsodium.gitbook.io/doc/roadmap)? I check it from time to time while waiting for XEdDSA support and noticed that the last update was four months ago. Are you having a development pause or are you focussing on other issues rather than new features?

**Comment by jedisct1** [comment]
XEdDSA will probably not be added, especially since key exchange can now be done using Ed25519.

I'll update the roadmap, thanks!

**Comment by Syndace** [comment]
That's sad to hear, I need XEdDSA for a project of mine and I currently use a very ugly self-made implementation. I was hoping for a clean, performant and secure implementation as part of a big crypto lib like this one. The only available implementation other than mine is licensed under GPL, which I don't want to use for my project. Any chance to change your mind about that?
