### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by djalillounis** [jedisct1/libsodium-doc#78]
Hello,

I am trying to link Sodium static using in visual studio.
I have add the lib and the sodium.h  but when i run the the test : 

int main()
{

	if (sodium_init() == -1) {
		return 1;
	}
    std::cout << "Hello World!\n"; 
}

I have a message from linker unsolved extern. I have updated the path  to the lib in my config.

any help on that  ?

Thank you

**Comment by jedisct1** [comment]
Maybe this can help: [https://stackoverflow.com/questions/23882112/how-to-add-the-static-libraries-to-the-project-in-visual-studio](https://stackoverflow.com/questions/23882112/how-to-add-the-static-libraries-to-the-project-in-visual-studio)

There are may other similar questions and responses about this on StackOverflow.
