### ISSUE TITLE
Update TFC URL and description

### ISSUE THREAD

**Issue by maqp** [jedisct1/libsodium-doc#81]
Thanks for listing the project! The [currently listed](https://libsodium.gitbook.io/doc/libsodium_users) URL and description are as follows:

https://github.com/maqp/tfc-nacl

Tinfoil Chat NaCl: TFC-NaCl is a high
assurance encryption plugin for the Pidgin IM client.

---
Stuff has changed since then and TFC is now more or less standalone, the current URL and description are:

https://github.com/maqp/tfc
Tinfoil Chat - Onion-routed, endpoint secure messaging system

**Comment by jedisct1** [comment]
Updated, thanks!

**Comment by maqp** [comment]
I apologize for the trouble but the project description still needs updating. TFC no longer piggybacks on Pidgin, it now communicates via Tor Onion Services. Also the name is no longer TFC-NaCl (which used to separate it from forks such as the one that used cascading encryption), but just TFC since there's only one version. It's still using libsodium's XChaCha20-Poly1305.

So could you please change the description to `Tinfoil Chat - Onion-routed, endpoint secure messaging system`.

**Comment by jedisct1** [comment]
Sorry for that. The description has been updated.

A pull request would have been easier :)

**Comment by maqp** [comment]
Yes, I'll make sure to do one next time. I'm terribly sorry and I don't mean to nitpick, but a typo found itself in the description's word "Onion", it's missing the letter `O`. If you can find the time at some point can you please fix it. I'd do a PR now but I feel for some reason it would be really impolite. Again, I'm sorry for the trouble and thank you for everything you do!

**Comment by jedisct1** [comment]
It's way faster for me to merge a PR, especially when I don't have a computer.
