### ISSUE TITLE
Missing documentation for crypto_secretbox_*

### ISSUE THREAD

**Issue by nsurbay** [jedisct1/libsodium-doc#90]
The commit c09f4687e0fda2e6fce54bf629334afb7061b913 doesn't include the file secretbox.md. The documentation of method crypto_secretbox_* isn't available in https://download.libsodium.org/doc/secret-key_cryptography/authenticated-encryption. 

Can you commit the missing file ?

**Comment by jedisct1** [comment]
Good catch, thanks!
