### ISSUE TITLE
Typo in the description of "Authenticated encryption"

### ISSUE THREAD

**Issue by mfrade** [jedisct1/libsodium-doc#95]
In the description of "Authenticated encryption" is the following sentence:

"A single key is used both to encrypt/**sign** and verify/decrypt messages. For this reason, it is critical to keep the key confidential."

**sign** implies non-repudiation, which is not the case with authenticated encryption, it should be replaced by **authenticate** in the description.

**Comment by jedisct1** [comment]
Thanks!
